"""Livemap geo engine: constrained walking fabric, enterability, isochrone."""

from .blindspot import (
    BLINDSPOT_RADIUS_M,
    DEFAULT_CATEGORIES,
    GRID_CELL_M,
    BlindspotPoi,
    blindspots,
    blindspots_from_geojson,
)
from .coords import (
    LocalProjection,
    bd09ll_to_gcj02,
    bd09ll_to_wgs84,
    gcj02_to_bd09ll,
    gcj02_to_wgs84,
    geohash5,
    haversine_m,
    wgs84_to_bd09ll,
    wgs84_to_gcj02,
)
from .enterability import (
    CATEGORY_BLOCKED,
    CATEGORY_ENTERABLE,
    CATEGORY_OPEN,
    CATEGORY_PODIUM,
    PODIUM_CORRIDOR_OFFSET_M,
    WALL_BUFFER_M,
    ClassifiedBuilding,
    classify_building,
    classify_buildings,
    podium_corridor_ring,
)
from .fabric import FabricLayers, MapFabricService, layers_to_geojson
from .graph import (
    SNAP_GRID_M,
    SNAP_MAX_DIST_M,
    SOURCE_BAIDU,
    SOURCE_OSM,
    SPEED_STEPS_M_MIN,
    SPEED_WALK_M_MIN,
    Edge,
    WalkGraph,
    build_graph,
    inject_baidu_polyline,
)
from .isochrone import (
    ISOCHRONE_BUFFER_M,
    IsochroneResult,
    build_isochrone,
    cutoff_dijkstra,
    fast_mask,
    layers_from_one_run,
)
from .scoring import coverage_score, passed, search_radius
from .sector import (
    DIRECTIONS,
    SectorGap,
    SectorGapReport,
    circle_radius_m,
    compute_sector_gaps,
    diagnose_worst_sector,
    sector_gap_report,
)

__version__ = "0.1.0"

__all__ = [
    "BLINDSPOT_RADIUS_M",
    "CATEGORY_BLOCKED",
    "CATEGORY_ENTERABLE",
    "CATEGORY_OPEN",
    "CATEGORY_PODIUM",
    "DEFAULT_CATEGORIES",
    "DIRECTIONS",
    "GRID_CELL_M",
    "ISOCHRONE_BUFFER_M",
    "PODIUM_CORRIDOR_OFFSET_M",
    "SNAP_GRID_M",
    "SNAP_MAX_DIST_M",
    "SOURCE_BAIDU",
    "SOURCE_OSM",
    "SPEED_STEPS_M_MIN",
    "SPEED_WALK_M_MIN",
    "WALL_BUFFER_M",
    "BlindspotPoi",
    "ClassifiedBuilding",
    "Edge",
    "FabricLayers",
    "IsochroneResult",
    "LocalProjection",
    "MapFabricService",
    "SectorGap",
    "SectorGapReport",
    "WalkGraph",
    "bd09ll_to_gcj02",
    "bd09ll_to_wgs84",
    "blindspots",
    "blindspots_from_geojson",
    "build_graph",
    "build_isochrone",
    "circle_radius_m",
    "classify_building",
    "classify_buildings",
    "compute_sector_gaps",
    "coverage_score",
    "cutoff_dijkstra",
    "diagnose_worst_sector",
    "fast_mask",
    "gcj02_to_bd09ll",
    "gcj02_to_wgs84",
    "geohash5",
    "haversine_m",
    "inject_baidu_polyline",
    "layers_from_one_run",
    "layers_to_geojson",
    "passed",
    "podium_corridor_ring",
    "search_radius",
    "sector_gap_report",
    "wgs84_to_bd09ll",
    "wgs84_to_gcj02",
]
